kasecato/vscode-intellij-idea-keybindings

- .travis.yml
- README.md
> fix travis

- README.md
- package.json
- src/package-with-comment.json
- src/tool/gene-keybind-markdown.js
> fixed readme

- README.md
- src/package-with-comment.json
- add `Move Statement Down` command
- add `Move Statement Up` command
> Add new key commands

- README.md
- src/package-with-comment.json
> Add 'Delete Line' command

- package.json
This is a suggestion to help people find the extension.
> Added IntelliJ products to package.json

- README.md
This is a suggestion to help people find the extension.
> Added JetBrains products to README

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/package-with-comment.json
Open Highlighted File (Explorer)
> Open Highlighted File (Explorer)

- README.md
- package.json
- src/package-with-comment.json
This PR adds support for extract method and extract constant within VSCode.
> Add refactor keybindings for extract method and extract constant.

- package.json
Fixes https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/115
> Update git sync command

- README.md
- package.json
- src/package-with-comment.json
Enables shortcut to functionality recently added in VSCode updates
> Enables 'navigate to last edit' shortcut

- package.json
- src/package-with-comment.json
Ref: https://github.com/Microsoft/vscode/issues/28383
> Updated "VCS quick popup"

- src/package-with-comment.json
https://www.jetbrains.com/help/idea/undo-changes.html#revert-local-changes
> Revert uncommitted changes shortcut

- CHANGELOG.md
- README.md
- resource/default/Mac/VSCode.json
- resource/default/Windows/IntelliJ.xml
- resource/default/Windows/VSCode.json
- src/extension.ts
- src/importer/model/OS.ts
- src/importer/reader/FileOpenDialog.ts
- src/importer/reader/Picker.ts
https://user-images.githubusercontent.com/10364603/105785059-6998a080-5fbd-11eb-9ac9-793f30226f64.mov
> #67/windows

- package.json
- src/extension.ts
- src/package-with-comment.json
- os : ubuntu
- version: 1.2.0
- debug extension from source: not repro
- install from vsix: not repro
- install from vscode market: repro
> Fixed #201 Fresh install could not find an import command

- README.md
- package.json
- resource/ActionIdCommandMapping.json
- resource/default/Linux/IntelliJ.xml
- resource/default/Mac/IntelliJ.xml
- resource/default/Windows/IntelliJ.xml
- src/package-with-comment.json
See #170 
See also https://github.com/microsoft/vscode/issues/5280
> Add search everywhere #170

- package.json
- resource/ActionIdCommandMapping.json
- resource/default/Linux/VSCode.json
- resource/default/Mac/VSCode.json
- resource/default/Windows/VSCode.json
- src/package-with-comment.json
> #213 fix the cmd+e trying to quickly open recent projects

- package.json
- resource/ActionIdCommandMapping.json
- resource/default/Linux/VSCode.json
- resource/default/Mac/VSCode.json
- resource/default/Windows/VSCode.json
- src/package-with-comment.json
See https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/213#issuecomment-801546096 for more detail
> Fix regression in recent files

- README.md
- package.json
- src/package-with-comment.json
Code action "Move..." is available when cursor is on signature of a class/method.
https://user-images.githubusercontent.com/2351748/121296813-d8024d80-c923-11eb-9510-6d6c0150ce75.mp4
> add keymap for Move

- README.md
- package.json
- src/package-with-comment.json
> Support restore default layout

- README.md
- package.json
- src/package-with-comment.json
> Support compare files

- README.md
- package.json
- src/package-with-comment.json
> Support stop when debugging

- package.json
- src/package-with-comment.json
fix regression #248 https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/276
> fix regression editor.action.formatDocument

- package.json
- src/package-with-comment.json
> Fixed #310 that Show Next Change is mapped instead of Go to Next Change

- package.json
- src/package-with-comment.json
> Fixed #233 that Commenting to move to next line as in Idea

- package.json
- src/package-with-comment.json
> Revert #233

- src/package-with-comment.json
> copyFilePath: add !terminalFocus to condition

- package.json
- src/package-with-comment.json
Add #368
ref. https://code.visualstudio.com/api/extension-guides/workspace-trust
> Add #368 that enable extension even in Non Trusted mode
