kasecato/vscode-intellij-idea-keybindings

package.json
src/package-with-comment.json

fixed #8 Command workbench.files.action.closeFile is now deprecated

---

README.md
package.json
src/package-with-comment.json

These keybindings are wonderfully helpful for multi-cursor editing. Make a selection, then hit `ctrl+g` on Mac to hop to the next occurrence. Very nice when traditional refactoring keybindings don't quite work for the circumstance.

Add select / unselect next occurrence keybindings

---

package.json

VSCode supports the `^1.7.0` syntax, not the `1.7.x` one.
This PR fixes that. I suggest to republish this extension to the store, so your users are able to install the latest version.
I will do Microsoft/vscode-vsce#143 so this doesn't happen in the future.

Update package.json with a compatible engine

---

src/package-with-comment.json

alt+9 was displaying warning "command 'workbench.view.git' not found"
As per https://github.com/Microsoft/vscode/issues/28383 thread, 'workbench.view.git' changed to 'workbench.view.scm'.
Updated same.

Updated mapping as per https://github.com/Microsoft/vscode/issues/28383

---

package.json
src/package-with-comment.json

Keep getting errors that `workbench.action.git.input-commit` doesn't exist. Having played with it locally it seems it's now `git.commitAll` so fix `cmd+k` to use the new command

fix cmd+k commit shortcut

---

README.md
package.json
src/package-with-comment.json

Replaced `workbench.action.openRecent` command with `workbench.action.quickOpenNavigateNext` that better reflects IntelliJ's `CMD+E` shortcut's behaviour
Edit: Turns out the problems with shortcuts not working often occurs when too many actions are bound to a single shortcut. In case of `CMD+E`, to make it work I had to remove the default binding to `actions.find` and `workbench.action.openRecent`.

#97 - Changed CMD+E to show Recent Files not Recent Projects popup

---

package.json
src/package-with-comment.json

Should be ```workbench.action.terminal.focus``` because the present command implementation ```workbench.action.terminal.toggleTerminal``` actually toggles the terminal but it does not focus it like it does on IntelliJ.

Fix terminal focus

---

README.md
package.json
src/package-with-comment.json

I slightly updated a `when` condition in triggerSuggest command.
Now, it looks like the default one in VSCode. There was two triggerSuggest bindings to the same `ctrl+space` but only with different `when` condition.
This was causing a *loading* message when you hit `ctrl+space` right after VSCode showed suggestions:
Now, it should behave normally.

Fixed triggerSuggest condition

---

README.md
package.json
src/package-with-comment.json

Resolves issue #127 
IntelliJ has the hotkey for Alt+Home for getting into the breadcrumbs, this functionality is added in VS Code as well now.

Alt Home hotkey for focusing the breadcrumbs

---

package.json

I think this should fix the cmd+n not opening a new untitled file

Fix cmd+n not opening new untitled file

---

README.md
package-lock.json
package.json
src/package-with-comment.json

Add `Column Selection Mode` shortcut.
- Linux/Windows: <kbd>Shift</kbd> + <kbd>Ctrl</kbd> + <kbd>8</kbd>
- Mac: <kbd>Shift</kbd> + <kbd>Cmd</kbd> + <kbd>8</kbd>

Add column selection shortcut

---

package.json
resource/default/Linux/VSCode.json
resource/default/Mac/VSCode.json
resource/default/Windows/VSCode.json
src/package-with-comment.json

fixes Ctrl/Cmd+Shift+F no longer filling the selected text into the search field when the search pane currently is not active
fixes https://github.com/microsoft/vscode/issues/119860
the issue was introduced by a change in VSCode: https://code.visualstudio.com/updates/v1_54#_changes-to-workspace-search-actions
related: https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/39

fixes Ctrl/Cmd+Shift+F due to change in VSCode

---

package.json
src/package-with-comment.json

Shift shift in IntelliJ allows you to search for file names and symbols.
Whilst it isn't an exact match, workbench.action.quickOpen allows you to search by file name, and if you know the file name, also search for symbols using @.
It's not as powerful as the IntelliJ search, but I think it is a better match than bringing up the command palette?

Update the shift shift 'Search Anywhere' command to call quickOpen

---

package.json

The keybindings created by Microsoft seem to all use the "keymap" keyword, adding this keyword here:
https://github.com/microsoft/vscode-sublime-keybindings/blob/main/package.json
https://github.com/microsoft/vscode-atom-keybindings/blob/main/package.json

Adding the keymap keyword to package.json

---

README.md
package.json
resource/ActionIdCommandMapping.json
resource/default/Linux/IntelliJ.xml
resource/default/Linux/VSCode.json
resource/default/Mac/IntelliJ.xml
resource/default/Mac/VSCode.json
resource/default/Windows/IntelliJ.xml
resource/default/Windows/VSCode.json
src/package-with-comment.json

Since "Show Call Hierarchy" is supported in [references-view](https://github.com/microsoft/vscode-references-view), which is the VSCode's build-in extension. We can add intellij keybindings support for call hierarchy.

Add keymap for call hierarchy

---

README.md
package.json
src/package-with-comment.json

In vscode-java extension, it uses the same code action to override/implement methods. Without this shortcut, you can find it via 
right click -> source actions... -> override/implement methods
https://user-images.githubusercontent.com/2351748/121289468-9075c480-c917-11eb-9734-203eaed6f858.mp4

add shortcut to override/implement methods

---

README.md
package.json
resource/ActionIdCommandMapping.json
resource/default/Linux/IntelliJ.xml
resource/default/Linux/VSCode.json
resource/default/Mac/IntelliJ.xml
resource/default/Mac/VSCode.json
resource/default/Windows/IntelliJ.xml
resource/default/Windows/VSCode.json
src/package-with-comment.json

VS Code provides a native command `editor.action.organizeImports`. 
https://user-images.githubusercontent.com/2351748/121293740-b3f03d80-c91e-11eb-9c4b-970c86b3beb5.mp4

add shortcut to optimize imports

---

README.md
package.json
resource/ActionIdCommandMapping.json
resource/default/Linux/IntelliJ.xml
resource/default/Linux/VSCode.json
resource/default/Mac/IntelliJ.xml
resource/default/Mac/VSCode.json
resource/default/Windows/IntelliJ.xml
resource/default/Windows/VSCode.json
src/package-with-comment.json

Type hierarchy has been supported by vscode java extension. See https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#0770-april-15th-2021
https://user-images.githubusercontent.com/2351748/121294638-5230d300-c920-11eb-98ee-50389e9a613f.mp4

add keymap for type hierarchy

---

README.md
package-lock.json
package.json
src/package-with-comment.json

In IntelliJ, if the mouse focuses on the editor, the key `alt+insert` should open a Generate code... menu (Source Action in VS Code), but if the mouse focuses on the project explorer, the key should open a new file menu. This PR tries to fix it.

`alt+insert` should have proper commands for different components

---

README.md
package.json
src/package-with-comment.json

the default of intellij `Column Selection mode` in windows should be `alt+shift+insert`

fix column selection mode

---

README.md
package.json
src/package-with-comment.json

Since extract field refactor has been supported in VS Code Java support, see: https://github.com/redhat-developer/vscode-java/pull/971, we can enable this.

Support Extract Field

---

README.md
package.json
src/package-with-comment.json

Since extract constant refactor has been supported in VS Code Java support, see: https://github.com/redhat-developer/vscode-java/pull/965, we can enable this.

Support extract constant

---

package.json
src/package-with-comment.json

in VS Code, we can use `workbench.debug.action.focusBreakpointsView` to focus the specific breakpoints view, not the debug view container.

Fix view breakpoints

---

README.md
package.json
src/package-with-comment.json

IntelliJ:
VSCode:
Go to Test feature has been support in [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test), which is included by [extension pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), the default recommendation extension for Java project in VS Code. Here I just add a when clause `java:testRunnerActivated` to avoid command missing bug.

Support Go to Test

---

README.md
package.json
src/package-with-comment.json

Since VS Code Java support has supported go to super implementation, see: https://github.com/redhat-developer/vscode-java/pull/1395
This feature is available when Java language server started, so I add a when clause `java:serverMode == Standard` to avoid missing command bug.

Support go to supermethod

---

package.json
src/package-with-comment.json

In vscode, cmd+shift+f does find in files when cmd+shift+f is pressed, except for when a folder is selected, in which case it does find in folder.
With the intellij bindings, we only being cmd+shift+f to find in files - I think this should be set up to run in a way similar to vscode core, as otherwise we are loosing functionality?

Add support for the find in folder alternative command

---

README.md
package.json
src/package-with-comment.json
src/tool/gene-keybind-markdown.js

First step at anding some Dart specific support to the keybindings to help out Dart/Flutter users that are used to IntelliJ keybindings. 
To land this, I also fixed bug where duplicate lines in the README would appear if there were
multiple entries for the same keyboard shortcut as this was impacting adding adding a Dart shortcut for ctrl+u as well as one existing case.

Add Dart version of Go to super-method/super-class (ctrl+u)

---

package.json

Currently, when opening a remote project (ssh/wsl), the plugin does not work and must be reinstalled or `remote.extensionKind` declared in the configuration. But as far as I know, the keymap should work as a UI plugin so that no special handling is required when opening remote projects
ref: <https://code.visualstudio.com/api/advanced-topics/remote-extensions#installing-a-development-version-of-your-extension>

feat: declare the plugin as a UI extension

---

.vscode/settings.json
package.json
src/package-with-comment.json

IntelliJ has a set of 4 commands that are used when `option+shift+f` is pressed to run format document, however, only 1 of them is mapped to `cmd+option+l`.
This PR updating the keybindings to include all the format document commands in their various permutations.

Include the full set of VS Code "format document" commands

---

src/importer/parser/IntelliJXmlParser.ts

Use `Array.forEach` instead of for-in to avoid iterate over internal properties of `keystorkeElements`. It will cause a crash because `keystrokeIndex` will be `'distinct'` instead of real index, and it will make `keyboardShortcutElement` to be a function. `firstKeystrokeAttr` & `secondKeystrokeAttr` will be undefined.

Fix a bug which will cause failed

---

README.md
package.json
src/package-with-comment.json

Potential solution for https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/300
Not sure about the wording in the readme file - but let me know what you think about this as an approach?

Add support for `Use "CamelHumps" words`

---

README.md
package.json
src/extension.ts
src/importer/extension/IntellijExtension.ts
src/package-with-comment.json

This PR introduces the "Open in Opposite Group" feature, which allows users to open the active editor tab in the opposite editor group with a single command. This functionality enhances navigation efficiency and aligns with similar features found in IntelliJ IDEA.
- Added a new command `intellij.openInOppositeGroup` in `IntellijExtension` class.
- Registered the new command in the extension's `activate` function.
- Updated `package.json` to include the new command and its keybindings.
- Ensured the command maintains focus on the newly opened editor tab and toggles back when invoked again.
This feature is expected to significantly improve user experience for those working with multiple files across different editor groups, making it easier to compare and edit files side by side.
- Manual …

feat: Implement "Open in Opposite Group" command

---

README.md
package.json
src/package-with-comment.json

Perform the equivalent of IntelliJ ‘Hide Active Tool Window’ by hiding each of the sidebar, secondary sidebar or panel when focused.
Implements https://www.jetbrains.com/help/idea/tool-windows.html#hide_active
Fixes #103.

Update shift+escape to Hide Active Tool Window

---

README.md
package.json
src/package-with-comment.json

Add diff pane focus toggle to implement the IntelliJ shortcut for ‘[Select Opposite Diff Pane](https://www.jetbrains.com/help/idea/reference-keymap-win-default.html#diff_viewer)’.

Implement Select Opposite Diff Pane

---

README.md
package.json
src/package-with-comment.json

Fixes #65 by inserting a semicolon at the end of the line if language is JavaScript (or TypeScript) and semicolons are configured as required using the existing `javascript.format.semicolons` configuration option in the JavaScript extension.

Complete current statement with semicolon if JS and configured

---

README.md
package.json
src/package-with-comment.json

Add support for Run Anything (https://www.jetbrains.com/help/idea/running-anything.html) on double ctrl to open the Run Task picker.

Support Run Anything shortcut on double ctrl

---

README.md
package.json
src/package-with-comment.json

Added [Go to Next/Prev Symbol Highlight support](https://www.jetbrains.com/help/idea/find-highlight-usages.html#usages_in_file).
close #372

Add Go to Next/Prev Symbol Highlight support

---

README.md
src/package-with-comment.json

One of my most used shortcut in IntelliJ was missing. Jumping from a git diff view to the actual file.

Add shortcut for f4 to jump to source
